"""agregar campos coced y contactoEmergencia a entrenadores

Revision ID: 01fc94b7032f
Revises: 8f1a3b5c7d9e
Create Date: 2026-06-12 11:13:31.595512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fc94b7032f'
down_revision: Union[str, Sequence[str], None] = '8f1a3b5c7d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrenadores', sa.Column('coced', sa.String(), nullable=True))
    op.add_column('entrenadores', sa.Column('contactoEmergencia', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrenadores', 'contactoEmergencia')
    op.drop_column('entrenadores', 'coced')
    # ### end Alembic commands ###
