"""agregar fechaInicio fechaFin evaluacion a entrenadores y fechas a devoluciones de jugadores

Revision ID: 06ec3caa836f
Revises: 01fc94b7032f
Create Date: 2026-06-12 11:28:48.953024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ec3caa836f'
down_revision: Union[str, Sequence[str], None] = '01fc94b7032f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrenadores', sa.Column('fechaInicio', sa.Date(), nullable=True))
    op.add_column('entrenadores', sa.Column('fechaFin', sa.Date(), nullable=True))
    op.add_column('entrenadores', sa.Column('evaluacion', sa.String(), nullable=True))
    op.add_column('jugadores', sa.Column('devolucion1_fechaInicio', sa.Date(), nullable=True))
    op.add_column('jugadores', sa.Column('devolucion1_fechaFin', sa.Date(), nullable=True))
    op.add_column('jugadores', sa.Column('devolucion2_fechaInicio', sa.Date(), nullable=True))
    op.add_column('jugadores', sa.Column('devolucion2_fechaFin', sa.Date(), nullable=True))
    op.add_column('jugadores', sa.Column('devolucion3_fechaInicio', sa.Date(), nullable=True))
    op.add_column('jugadores', sa.Column('devolucion3_fechaFin', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jugadores', 'devolucion3_fechaFin')
    op.drop_column('jugadores', 'devolucion3_fechaInicio')
    op.drop_column('jugadores', 'devolucion2_fechaFin')
    op.drop_column('jugadores', 'devolucion2_fechaInicio')
    op.drop_column('jugadores', 'devolucion1_fechaFin')
    op.drop_column('jugadores', 'devolucion1_fechaInicio')
    op.drop_column('entrenadores', 'evaluacion')
    op.drop_column('entrenadores', 'fechaFin')
    op.drop_column('entrenadores', 'fechaInicio')
    # ### end Alembic commands ###
