"""agregar devoluciones a jugador y lapso devoluciones a categoria

Revision ID: 2392d82adee5
Revises: bbc9125c68a9
Create Date: 2026-06-12 11:40:19.860554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2392d82adee5'
down_revision: Union[str, Sequence[str], None] = 'bbc9125c68a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('lapsoDevolucionesInicio', sa.Date(), nullable=True))
    op.add_column('categorias', sa.Column('lapsoDevolucionesFin', sa.Date(), nullable=True))
    op.add_column('jugadores', sa.Column('devoluciones', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jugadores', 'devoluciones')
    op.drop_column('categorias', 'lapsoDevolucionesFin')
    op.drop_column('categorias', 'lapsoDevolucionesInicio')
    # ### end Alembic commands ###
