"""agregar columnas de nombre original de archivos

Revision ID: 43bcc0d95744
Revises: 2392d82adee5
Create Date: 2026-06-13 18:46:42.125151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43bcc0d95744'
down_revision: Union[str, Sequence[str], None] = '2392d82adee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asistencias', sa.Column('archivo_original', sa.String(), nullable=True))
    op.add_column('entrenadores', sa.Column('certificado_original', sa.String(), nullable=True))
    op.add_column('entrenadores', sa.Column('delitosSexuales_original', sa.String(), nullable=True))
    op.add_column('entrenadores', sa.Column('tarjetaProfesional_original', sa.String(), nullable=True))
    op.add_column('entrenadores', sa.Column('certificadoPrimerCorrespondiente_original', sa.String(), nullable=True))
    op.add_column('entrenadores', sa.Column('evaluacion_original', sa.String(), nullable=True))
    op.add_column('jugadores', sa.Column('devolucion1_original', sa.String(), nullable=True))
    op.add_column('jugadores', sa.Column('devolucion2_original', sa.String(), nullable=True))
    op.add_column('jugadores', sa.Column('devolucion3_original', sa.String(), nullable=True))
    op.add_column('jugadores', sa.Column('devoluciones_original', sa.String(), nullable=True))
    op.add_column('planeaciones', sa.Column('archivo_original', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planeaciones', 'archivo_original')
    op.drop_column('jugadores', 'devoluciones_original')
    op.drop_column('jugadores', 'devolucion3_original')
    op.drop_column('jugadores', 'devolucion2_original')
    op.drop_column('jugadores', 'devolucion1_original')
    op.drop_column('entrenadores', 'evaluacion_original')
    op.drop_column('entrenadores', 'certificadoPrimerCorrespondiente_original')
    op.drop_column('entrenadores', 'tarjetaProfesional_original')
    op.drop_column('entrenadores', 'delitosSexuales_original')
    op.drop_column('entrenadores', 'certificado_original')
    op.drop_column('asistencias', 'archivo_original')
    # ### end Alembic commands ###
