"""agregar columnas password y rol a entrenadores

Revision ID: 9e8088b4746f
Revises: e205a400ef9b
Create Date: 2026-06-11 12:30:06.722358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8088b4746f'
down_revision: Union[str, Sequence[str], None] = 'e205a400ef9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrenadores', sa.Column('password', sa.String(), nullable=True))
    op.add_column('entrenadores', sa.Column('rol', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrenadores', 'rol')
    op.drop_column('entrenadores', 'password')
    # ### end Alembic commands ###
