"""eliminar campos certificadoPrimerCorrespondiente y evaluacion de entrenadores

Revision ID: b91b5c8ffb4e
Revises: ecc6abc66141
Create Date: 2026-06-13 21:52:59.179417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91b5c8ffb4e'
down_revision: Union[str, Sequence[str], None] = 'ecc6abc66141'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrenadores', 'evaluacion_original')
    op.drop_column('entrenadores', 'certificadoPrimerCorrespondiente')
    op.drop_column('entrenadores', 'certificadoPrimerCorrespondiente_original')
    op.drop_column('entrenadores', 'evaluacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrenadores', sa.Column('evaluacion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entrenadores', sa.Column('certificadoPrimerCorrespondiente_original', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entrenadores', sa.Column('certificadoPrimerCorrespondiente', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entrenadores', sa.Column('evaluacion_original', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
