"""agregar lapsoInicio lapsoFin a planeaciones

Revision ID: bbc9125c68a9
Revises: 06ec3caa836f
Create Date: 2026-06-12 11:34:25.685106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc9125c68a9'
down_revision: Union[str, Sequence[str], None] = '06ec3caa836f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planeaciones', sa.Column('lapsoInicio', sa.Date(), nullable=True))
    op.add_column('planeaciones', sa.Column('lapsoFin', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planeaciones', 'lapsoFin')
    op.drop_column('planeaciones', 'lapsoInicio')
    # ### end Alembic commands ###
