"""encriptar datos sensibles en entrenadores y jugadores

Revision ID: c64c9ba30b60
Revises: b91b5c8ffb4e
Create Date: 2026-06-13 22:05:16.940619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c64c9ba30b60'
down_revision: Union[str, Sequence[str], None] = 'b91b5c8ffb4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
