"""Se crean Tablas en entorno de pruebas

Revision ID: c9b32c7618f3
Revises: 
Create Date: 2026-03-15 21:53:53.135103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9b32c7618f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrenadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('tipoDocumento', sa.String(), nullable=True),
    sa.Column('documento', sa.String(), nullable=True),
    sa.Column('certificado', sa.String(), nullable=True),
    sa.Column('delitosSexuales', sa.String(), nullable=True),
    sa.Column('tarjetaProfesional', sa.String(), nullable=True),
    sa.Column('certificadoPrimerCorrespondiente', sa.String(), nullable=True),
    sa.Column('celular', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('idEntrenador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEntrenador'], ['entrenadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fechaCreacion', sa.Date(), nullable=True),
    sa.Column('fechaCargado', sa.Date(), nullable=True),
    sa.Column('idEntrenador', sa.Integer(), nullable=True),
    sa.Column('idCategoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCategoria'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['idEntrenador'], ['entrenadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jugadores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('nacionalidad', sa.String(), nullable=True),
    sa.Column('tipoDocumento', sa.String(), nullable=True),
    sa.Column('documento', sa.String(), nullable=True),
    sa.Column('fechaNacimiento', sa.Date(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('dorsal', sa.Integer(), nullable=True),
    sa.Column('contactoEmergencia', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('fechaIngreso', sa.Date(), nullable=True),
    sa.Column('fechaSalida', sa.Date(), nullable=True),
    sa.Column('devolucion1', sa.String(), nullable=True),
    sa.Column('devolucion2', sa.String(), nullable=True),
    sa.Column('devolucion3', sa.String(), nullable=True),
    sa.Column('torneo', sa.String(), nullable=True),
    sa.Column('idCategoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCategoria'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planeaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fechaInicio', sa.Date(), nullable=True),
    sa.Column('fechaFin', sa.Date(), nullable=True),
    sa.Column('fechaCarga', sa.Date(), nullable=True),
    sa.Column('idCategoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCategoria'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planeaciones')
    op.drop_table('jugadores')
    op.drop_table('asistencias')
    op.drop_table('categorias')
    op.drop_table('entrenadores')
    # ### end Alembic commands ###
