"""actulizamos tablas de DB para el cargue de archivos

Revision ID: df8b903da144
Revises: c9b32c7618f3
Create Date: 2026-03-20 09:21:12.801122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8b903da144'
down_revision: Union[str, Sequence[str], None] = 'c9b32c7618f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asistencias', sa.Column('archivo', sa.String(), nullable=True))
    op.add_column('planeaciones', sa.Column('archivo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planeaciones', 'archivo')
    op.drop_column('asistencias', 'archivo')
    # ### end Alembic commands ###
