"""agregar columna archivo a asistencias y planeaciones

Revision ID: e205a400ef9b
Revises: df8b903da144
Create Date: 2026-03-20 12:56:07.460186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e205a400ef9b'
down_revision: Union[str, Sequence[str], None] = 'df8b903da144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
