"""eliminar columna fechaCreacion de asistencias

Revision ID: ecc6abc66141
Revises: 43bcc0d95744
Create Date: 2026-06-13 19:32:37.951859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecc6abc66141'
down_revision: Union[str, Sequence[str], None] = '43bcc0d95744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asistencias', 'fechaCreacion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asistencias', sa.Column('fechaCreacion', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
